### ISSUE TITLE
Gunicorn does not start the Flask app with DEBUG set to False

### ISSUE THREAD

**Issue by haimat** [app-generator/flask-gradient-able#2]
I deployed our application based on your **Gradient Able** framework to our server, setting `DEBUG=False` in the `.env` file. However, after starting the app via `gunicorn` the global `DEBUG` config option in the Flask app is still set to `True`. It does work, however, when hard-coding the value in `run.py`, instead of the following line:

    DEBUG = config("DEBUG", default=False)

Is this a bug or a feature?

**Comment by app-generator** [comment]
Fixed in **v1.0.4**.
Please update.
